const nodemailer = require('nodemailer');

/**
 * Creates and returns a configured nodemailer transporter.
 * Reads credentials from environment variables so secrets never live in code.
 *
 * Required .env keys:
 *   EMAIL_HOST        — e.g. 'smtp.gmail.com'
 *   EMAIL_PORT        — e.g. 587
 *   EMAIL_USER        — your Gmail / SMTP username
 *   EMAIL_PASS        — your Gmail App Password or SMTP password
 *   EMAIL_FROM_NAME   — display name, e.g. 'MedTime Health'
 */
function createTransporter() {
  // Fall back to Ethereal (catch-all testing SMTP) when env vars are absent
  const host = process.env.EMAIL_HOST || 'smtp.ethereal.email';
  const port = parseInt(process.env.EMAIL_PORT || '587', 10);
  const user = process.env.EMAIL_USER || '';
  const pass = process.env.EMAIL_PASS || '';

  return nodemailer.createTransport({
    host,
    port,
    secure: port === 465, // true for 465, false for other ports (STARTTLS)
    auth: { user, pass },
    tls: {
      // Do not fail on invalid / self-signed certs in dev environments
      rejectUnauthorized: process.env.NODE_ENV === 'production'
    }
  });
}

/**
 * Sends a professional clinical-adherence report email to the patient's doctor.
 *
 * @param {string} doctorEmail   — Recipient's email address
 * @param {string} doctorName    — Recipient's display name (used in greeting)
 * @param {string} patientName   — Patient's name (used in body & attachment filename)
 * @param {Buffer} pdfBuffer     — In-memory PDF Buffer generated by pdfmake
 * @returns {Promise<object>}    — Nodemailer send result info object
 */
async function sendDoctorReportEmail(doctorEmail, doctorName, patientName, pdfBuffer) {
  const transporter = createTransporter();
  const fromName = process.env.EMAIL_FROM_NAME || 'MedTime Health';
  const fromAddress = process.env.EMAIL_USER || 'noreply@medtime.health';
  const safeFilename = `${patientName.replace(/\s+/g, '_')}_Clinical_Report.pdf`;
  const reportDate = new Date().toLocaleDateString('en-IN', {
    day: '2-digit', month: 'long', year: 'numeric'
  });

  const htmlBody = `
  <!DOCTYPE html>
  <html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>MedTime Clinical Report</title>
    <style>
      body { margin: 0; padding: 0; background: #f4f7fb; font-family: 'Segoe UI', Arial, sans-serif; color: #2d3748; }
      .wrapper { max-width: 600px; margin: 32px auto; background: #ffffff; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 24px rgba(0,0,0,0.08); }
      .header { background: linear-gradient(135deg, #4A90D9 0%, #6C5CE7 100%); padding: 36px 40px; text-align: center; }
      .header h1 { margin: 0; font-size: 28px; font-weight: 700; color: #ffffff; letter-spacing: -0.5px; }
      .header p  { margin: 8px 0 0; font-size: 14px; color: rgba(255,255,255,0.8); }
      .badge { display: inline-block; margin-top: 16px; padding: 6px 16px; background: rgba(255,255,255,0.2); border-radius: 20px; font-size: 12px; color: #fff; font-weight: 600; text-transform: uppercase; letter-spacing: 1px; }
      .body { padding: 40px; }
      .greeting { font-size: 17px; color: #2d3748; margin-bottom: 20px; line-height: 1.6; }
      .highlight { background: #eef4ff; border-left: 4px solid #4A90D9; border-radius: 0 8px 8px 0; padding: 16px 20px; margin: 24px 0; font-size: 15px; color: #1a365d; font-weight: 500; }
      .info-grid { display: flex; gap: 16px; margin: 24px 0; }
      .info-box { flex: 1; background: #f8fafc; border-radius: 10px; padding: 16px; border: 1px solid #e2e8f0; }
      .info-box .label { font-size: 11px; color: #718096; text-transform: uppercase; letter-spacing: 1px; font-weight: 600; margin-bottom: 4px; }
      .info-box .value { font-size: 15px; color: #2d3748; font-weight: 700; }
      .cta { text-align: center; margin: 32px 0 20px; }
      .cta p { font-size: 14px; color: #718096; margin: 0 0 6px; }
      .divider { border: none; border-top: 1px solid #e2e8f0; margin: 28px 0; }
      .footer { padding: 24px 40px; background: #f8fafc; text-align: center; font-size: 12px; color: #a0aec0; line-height: 1.6; }
      .footer a { color: #4A90D9; text-decoration: none; }
    </style>
  </head>
  <body>
    <div class="wrapper">
      <div class="header">
        <h1>➕ MedTime</h1>
        <p>Autonomous Clinical Adherence Report</p>
        <span class="badge">Automated • ${reportDate}</span>
      </div>
      <div class="body">
        <p class="greeting">
          Dear Dr. ${doctorName},
        </p>
        <div class="highlight">
          📋 Attached is the automated <strong>30-day clinical adherence report</strong> for your patient, 
          <strong>${patientName}</strong>.
        </div>
        <p style="font-size:15px; line-height:1.7; color:#4a5568;">
          This report was automatically compiled by the MedTime patient monitoring platform and includes 
          medication adherence rates, blood pressure and vitals trends, and any escalation events 
          recorded over the past 30 days.
        </p>
        <div class="info-grid">
          <div class="info-box">
            <div class="label">Patient</div>
            <div class="value">${patientName}</div>
          </div>
          <div class="info-box">
            <div class="label">Report Period</div>
            <div class="value">Last 30 Days</div>
          </div>
          <div class="info-box">
            <div class="label">Generated</div>
            <div class="value">${reportDate}</div>
          </div>
        </div>
        <p style="font-size:14px; color:#718096; line-height:1.6;">
          The full PDF report is attached to this email as 
          <strong>${safeFilename}</strong>. 
          No action is required unless the report flags a concern that warrants a clinical review.
        </p>
        <hr class="divider" />
        <p style="font-size:13px; color:#a0aec0; text-align:center;">
          This is an automated message from the MedTime platform. Your patient has opted into 
          monthly doctor reporting. To unsubscribe, the patient can update their settings in the app.
        </p>
      </div>
      <div class="footer">
        <strong>MedTime Health Platform</strong><br />
        Empowering patients. Keeping doctors informed.<br />
        <a href="https://medtime.health">medtime.health</a> &nbsp;|&nbsp;
        This report is for informational purposes only and does not replace a clinical diagnosis.
      </div>
    </div>
  </body>
  </html>
  `;

  const mailOptions = {
    from: `"${fromName}" <${fromAddress}>`,
    to: doctorEmail,
    subject: `[MedTime] 30-Day Clinical Report — ${patientName} (${reportDate})`,
    html: htmlBody,
    attachments: [
      {
        filename: safeFilename,
        content: pdfBuffer,       // In-memory Buffer — no disk I/O
        contentType: 'application/pdf'
      }
    ]
  };

  try {
    const info = await transporter.sendMail(mailOptions);
    console.log(`✅ Clinical report emailed to Dr. ${doctorName} <${doctorEmail}> — MessageId: ${info.messageId}`);

    // If using Ethereal (dev), log the preview URL
    const previewUrl = nodemailer.getTestMessageUrl(info);
    if (previewUrl) console.log(`   📬 Preview URL: ${previewUrl}`);

    return info;
  } catch (error) {
    console.error(`❌ Failed to send report email to ${doctorEmail}:`, error.message);
    throw error;
  }
}

module.exports = { sendDoctorReportEmail };
